Fix-brew-step (#453)
* fix brew step

diff --git a/build/ci.yaml b/build/ci.yaml
--- a/build/ci.yaml
+++ b/build/ci.yaml
@@ -242,16 +242,27 @@ steps:
     title: bump brew formula version
     image: codefresh/build-cli
     commands:
-      - echo "generate formula from template ..."
-      - sed -e "s/{{ version }}/${{VERSION}}/g" -e "s/{{ revision }}/${{CF_REVISION}}/g" ./brew/template.rb > ${{BREW_NAME}}.rb
-      - echo "Updating file in GitHub"
-      - FORMULA_SHA256=$(curl -X GET https://api.github.com/repos/codefresh-io/homebrew-cli/contents/Formula/${{BREW_NAME}}.rb | jq .sha)
       - |
-        curl -v -i -X PUT -H 'Authorization: token '$GITHUB_TOKEN'' -d "{ \
-          \"message\": \"update formula version $VERSION\", \
-          \"content\": \"$(openssl base64 -A -in ${{BREW_NAME}}.rb)\", \
-          \"sha\": $FORMULA_SHA256 \
-          }" https://api.github.com/repos/codefresh-io/homebrew-cli/contents/Formula/${{BREW_NAME}}.rb
+        echo "generate formula from template..."
+        sed -e "s/{{ version }}/${{VERSION}}/g" -e "s/{{ revision }}/${{CF_REVISION}}/g" ./brew/template.rb > ${{BREW_NAME}}.rb
+        echo "Updating file in GitHub"
+        FORMULA_SHA256=$(curl -X GET https://api.github.com/repos/codefresh-io/homebrew-cli/contents/Formula/${{BREW_NAME}}.rb \
+          -H "Authorization: token ${GITHUB_TOKEN}" \
+          -s | jq .sha)
+        echo "sha - ${FORMULA_SHA256}"
+        STATUS_CODE=$(curl -X PUT https://api.github.com/repos/codefresh-io/homebrew-cli/contents/Formula/${{BREW_NAME}}.rb \
+          -H "Authorization: token ${GITHUB_TOKEN}" \
+          -d "{ \
+            \"message\": \"update formula version to ${VERSION}\", \
+            \"content\": \"$(openssl base64 -A -in ${{BREW_NAME}}.rb)\", \
+            \"sha\": ${FORMULA_SHA256} \
+          }" -s -o response -w "%{http_code}")
+        echo "statusCode - ${STATUS_CODE}"
+        if [[ "$STATUS_CODE" -ge 300 ]]; then
+          cat ./response
+          echo "failed updating brew formula version"
+          exit 1
+        fi
     when:
       steps:
         - name: create_release_bin
